services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: test123
      POSTGRES_USER: postgres
      POSTGRES_DB: app2
    ports:
      - '5432:5432'
    volumes: 
      - postgres-data:/var/lib/postgresql/data
  backend:
    build: .
    container_name: backend
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: test123
      DB_NAME: app2
    ports:
      - '9000:9000'

volumes:
  postgres-data: